# Generated by Django 2.0.3 on 2018-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='token',
            field=models.CharField(default='', max_length=200, verbose_name='Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Nom', max_length=255, verbose_name='Nom de la playlist'),
            preserve_default=False,
        ),
    ]
