# Generated by Django 2.0.3 on 2018-03-28 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20180324_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_get',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière écoute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière mise à jour'),
            preserve_default=False,
        ),
    ]
