# Generated by Django 2.0.3 on 2018-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20180328_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True, verbose_name="Visible sur la page d'accueil"),
        ),
    ]
